### ISSUE TITLE
Downcasting support

### ISSUE THREAD

**Issue by hia3** [philippeb8/root_ptr#1]
Is it possible to have something similar to `std::dynamic_pointer_cast`? Or how do I convert `node_ptr<Base>` to `node_ptr<Derived>`?

**Comment by philippeb8** [comment]
Good question. I just fixed a bug in the code and now the downcasting works as follows:

    struct B
    {
        int i;
        
        B() : i(9) {}
    
        virtual ~B() {}
    };

    struct C : B
    {
    };

    [...]

    cout << "Downcasting:" << endl;
    {
        node_proxy x;
        node_ptr<C> p = make_node<B>(x);
        cout << p.get() << endl;
    }
    cout << endl;


Which outputs:

    Downcasting:
    0
    [2018-01-25 11:57:44.153631] [0x00007f6a72075b80] [info]    <cycle>: 0# 0x000055BE77D3AA6A in ./root_ptr_example1

Please see [https://github.com/philippeb8/root_ptr/blob/master/example/root_ptr_example1.cpp](https://github.com/philippeb8/root_ptr/blob/master/example/root_ptr_example1.cpp)

**Comment by philippeb8** [comment]
But I will add the proper `std::dynamic_pointer_cast` syntax in a following update.

**Comment by philippeb8** [comment]
Thanks for your patience. I just added `static_pointer_cast` and `dynamic_pointer_cast`. Here's the correct way to use it:

    cout << "Downcasting:" << endl;
    {
        node_proxy x;
        node_ptr<C> p = dynamic_pointer_cast<C>(make_node<B>(x));
        cout << p.get() << endl;
    }
    cout << endl;
